[2025-10-20T02:17:54.206+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gmm_segmentation_simple.run_gmm manual__2025-10-20T02:17:52.745923+00:00 [queued]>
[2025-10-20T02:17:54.210+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gmm_segmentation_simple.run_gmm manual__2025-10-20T02:17:52.745923+00:00 [queued]>
[2025-10-20T02:17:54.210+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T02:17:54.210+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-10-20T02:17:54.210+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T02:17:54.216+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_gmm> on 2025-10-20 02:17:52.745923+00:00
[2025-10-20T02:17:54.218+0000] {standard_task_runner.py:55} INFO - Started process 122 to run task
[2025-10-20T02:17:54.220+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gmm_segmentation_simple', 'run_gmm', 'manual__2025-10-20T02:17:52.745923+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/gmm_segmentation.py', '--cfg-path', '/tmp/tmpiq183a0_']
[2025-10-20T02:17:54.220+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask run_gmm
[2025-10-20T02:17:54.263+0000] {task_command.py:388} INFO - Running <TaskInstance: gmm_segmentation_simple.run_gmm manual__2025-10-20T02:17:52.745923+00:00 [running]> on host 2f7303ce5544
[2025-10-20T02:17:54.308+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=asad_waraich
AIRFLOW_CTX_DAG_ID=gmm_segmentation_simple
AIRFLOW_CTX_TASK_ID=run_gmm
AIRFLOW_CTX_EXECUTION_DATE=2025-10-20T02:17:52.745923+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-20T02:17:52.745923+00:00
[2025-10-20T02:17:54.343+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gmm_segmentation.py", line 23, in run_gmm_segmentation
    from sklearn.mixture import GaussianMixture
ModuleNotFoundError: No module named 'sklearn'
[2025-10-20T02:17:54.353+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gmm_segmentation_simple, task_id=run_gmm, execution_date=20251020T021752, start_date=20251020T021754, end_date=20251020T021754
[2025-10-20T02:17:54.360+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task run_gmm (No module named 'sklearn'; 122)
[2025-10-20T02:17:54.399+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-20T02:17:54.412+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
